### ISSUE TITLE
Toolbar.jsp produces bad xml

### ISSUE THREAD

**Issue by csrster** [iipc/openwayback#171]
We have been unable to replay m.facebook.com in proxy mode because Toolbar.jsp produces badly formed xml. We have tested a solution which seems to work: 
 1. The script body which starts around line 74 needs to be enclosed in a CDATA block because of the
use of unescaped characters like ">"
 1. The form which starts around line 188 has some unclosed <input> elements.

We'll be happy to submit a patch or pull request.

**Comment by anjackson** [comment]
okay to close this?

**Comment by PsypherPunk** [comment]
Fixed in #200.
