### ISSUE TITLE
Unix specific TMP-paths

### ISSUE THREAD

**Issue by RogerMathisen** [iipc/openwayback#172]
Some classes and test classes have references to Unix specific TMP-path, which will make them fail under Windows.

org.archive.wayback.liveweb.URLtoARCCacher
      The variable "DEFAULT_RECORDER_DIR" will not be valid under Windows.

org.archive.wayback.util.MonitoredFileSetTest
      The File variables "f1" and "f2" will not be valid.

org.archive.wayback.accesscontrol.ExternalExcluderTest
     The variable "configPath" is not valid under Windows, but is never used so the test does not fail.

Also 
org.archive.wayback.resourceindex.cdxserver.EmbeddedCDXServerIndexTest
    Fails because of CRLF differences on Windows and Unix comparing against "\n". This should be   
    investigated further to be sure that the actual class does not have the same problem.

**Comment by PsypherPunk** [comment]
Fixed in 0ad526ac7c4867e291ac28b4661f742a2c5a24ed.
