### ISSUE TITLE
Mememto: Mismatch between Memento Date & Embedded Date

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#177]
There is a sporadic issue wherein the datetime values returned via the `timemap` endpoint do not correspond to those in the URL, e.g.:

    <http://www.google-analytics.com/urchin.js>; rel="original",
    <http://www.webarchive.org.uk:80/wayback/archive/timemap/link/http://www.google-analytics.com/urchin.js>; rel="self"; type="application/link-format"; from="Wed, 30 Nov 2005 12:00:00 GMT"; until="Thu, 09 Oct 2014 09:21:30 GMT",
    ...
    <http://www.webarchive.org.uk:80/wayback/archive/20081124092242/http://www.google-analytics.com/urchin.js>; rel="memento"; datetime="Mon, 11 Jan 2012 20:47:20 GMT",
    ...

The issue has been discussed at length on the [user forum](https://groups.google.com/forum/#!topic/openwayback-dev/hLME0_b0nQQ). It is presently unclear whether the issue is happening in OpenWayback or within the [webarchive-commons](https://github.com/iipc/webarchive-commons/) dependency.

**Comment by kris-sigur** [comment]
@anjackson Did the PR #180 fix this or is this still broken?

**Comment by anjackson** [comment]
I believe this is resolved.
