### ISSUE TITLE
Handle 'Range Retrieval Requests'

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#179]
It would be useful if OpenWayback could handle 'Range Retrieval Requests', i.e. return an `Accept-Ranges` header and handle `Content-Range` requests.

The motivation for this is to facilitate playing videos straight out of WARC files (the above is, as far as I am aware, how the HTML5 video handles playback).

It's likely that the above would only really work with non-compressed (W)ARCs as one can't arbitrarily skip around in gzip streams; it might be possible to handle compressed records via some sort of caching but if at all possible this should probably wait for a later iteration.

**Comment by RogerMathisen** [comment]
Could this have been addressed by Internet Archive? 
Ref: https://github.com/internetarchive/wayback/issues/66

**Comment by kngenie** [comment]
internetarchive#66 just passes through Content-Range header field *recorded in the capture* to playback response. Wayback does not handle Content-Range request for itself.  It does not address this issue, I suppose.

**Comment by kngenie** [comment]
We hit this issue in our service, and implemented a limited support for Range request: https://github.com/internetarchive/wayback/issues/78
It has several limitations and can be slow for large data, but it's working good enough for the case at hand. I'll submit a pull request.
