### ISSUE TITLE
logging-config-path and config-path must be absolute on Tomcat 8

### ISSUE THREAD

**Issue by dmolesUC3** [iipc/openwayback#196]
In order to get OpenWayback 2.0.0 up and running under Tomcat 8.0.15 / Oracle JDK 8 / Mac OS 10.10, I had to change the default `logging-config-path` and `config-path` from relative to absolute paths:

```xml
    <context-param>
        <param-name>logging-config-path</param-name>
        <!-- <param-value>WEB-INF/classes/logging.properties</param-value> -->
        <param-value>/WEB-INF/classes/logging.properties</param-value>
    </context-param>
    <context-param>
        <param-name>config-path</param-name>
        <!-- <param-value>WEB-INF/wayback.xml</param-value> -->
        <param-value>/WEB-INF/wayback.xml</param-value>
    </context-param>
```

This looks to be a Tomcat issue, as `org.apache.catalina.webresources.StandardRoot.validate(String)` has a `path.startsWith("/")` check.

**Comment by anjackson** [comment]
Can I assume this syntax will work under Tomcat 6/7 as well as 8?

**Comment by dmolesUC3** [comment]
I've only got 8 on this box, so I don't know for sure. If you have a Tomcat 6/7 setup handy (surely somebody in this room does?), give it a try. :)

**Comment by PsypherPunk** [comment]
Tried this in Tomcat 7 (Windows) and it still works as expected.

**Comment by anjackson** [comment]
Cool, can you turn that into a pull request? Note that I've just synced up the ukwa fork so you'll need to update first.

**Comment by dmolesUC3** [comment]
Done!
