### ISSUE TITLE
Hardcoded Port Number

### ISSUE THREAD

**Issue by ibnesayeed** [iipc/openwayback#222]
Is there a reason why the port number is hardcoded in [the wayback.xml file](https://github.com/iipc/openwayback/blob/master/wayback-webapp/src/main/webapp/WEB-INF/wayback.xml#L155) instead of using the placeholder?

```xml
<bean name="+" class="org.archive.wayback.webapp.ServerRelativeArchivalRedirect">
  <property name="matchPort" value="8080" />
  <property name="useCollection" value="true" />
</bean>
```

Here `8080` could be `${wayback.url.port}`

**Comment by kris-sigur** [comment]
Probably just a remnant of 'old times'. We should change this.

**Comment by ibnesayeed** [comment]
I have tried fixing such hardcoded port and URL prefix entries in couple of files. PR is ready.
