### ISSUE TITLE
Failing test: testPadDateStr(org.archive.wayback.util.TimestampTest): padEnd expected:<...28...> but was:<...31...>

### ISSUE THREAD

**Issue by rossh** [iipc/openwayback#231]
Hi guys, I'm getting the following test failure:

Failed tests:   testPadDateStr(org.archive.wayback.util.TimestampTest): padEnd expected:<...28...> but was:<...31...>

This is happening because Timestamp.getDaysInMonthBound has a bug in it which doesn't return back the correct maximum day of the month for months which don't have a 29th, 30th and 31st e.g. February. We've fixed it and will do a pull request.

**Comment by kris-sigur** [comment]
This is a naughty little bug. Thanks for tracking it down. I'll see about getting this merged later today.
