### ISSUE TITLE
Not Rewriting <source /> Tags?

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#242]
We've an archived copy of [this](http://www.theguardian.com/commentisfree/video/2015/jan/28/polly-toynbee-david-cameron-dont-underestimate-ruthless-man-cuts) page.

The video plays but is leaking from the live web. However, this seems to be because OpenWayback (2.1.0) is not rewriting the `src` attributes of the `<source/>` tags.

**Comment by ldko** [comment]
Additionally, `src` attributes are not rewritten in some other HTML5 tags such as `<video/>` and `<audio/>`.
