### ISSUE TITLE
IDN support

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#27]
**S'sheet line:** 10
**For whom?** BNF, DN
**Notes:** CDX/indexing consequences? Need a test case. Heritrix issues, maybe just H1, so need H1 and H3 test cases.
**Est. Milestone:** 2.x.x

**Comment by johnerikhalse** [comment]
I've made a possible solution here: https://github.com/iipc/openwayback/tree/issue27_IDN
I am not sure if every aspect of IDN support is solved or if I have broken anything. It would be nice if somebody could build and test it. Please feel free to make any enhancements you like to it.

**Comment by kris-sigur** [comment]
PR #246 merged. Closing issue.
