### ISSUE TITLE
WatchedCDXSourceTest fails on MacOS X

### ISSUE THREAD

**Issue by kngenie** [iipc/openwayback#271]
Running mvn test on MacOS X 10.10.3 (Yosemite) with Oracle JDK 1.7.0u79, all of WatchedCDXSourceTest fails.

It appears WatchService on MacOS X is implemented by polling (`sun.nio.fs.PollingWatchService`), and default polling interval (_sensitivity_) is 10 seconds (!). So WatchedCDXSource cannot pick up FS change event within 100ms sleep in the test.

**Comment by kris-sigur** [comment]
[Issue about this on StackOverflow](https://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else)
