### ISSUE TITLE
Possible Canonicalization Problem on Some URLs

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#273]
We're seeing some odd behaviour when creating CDX indexes for some URLs. Specifically, using the out-of-the-box `cdx-indexer` script produces a line like the following:

    ic.c4assets.com/brands/freeformpictureitem/d9be3906-b707-4e32-beb6-d15047085aa4_625x352.jpg?interpolation=progressive-bicubic&output-quality=90&output-format=jpeg&crop=220px:298px;0,0px 20141215101520 http://ic.c4assets.com/brands/freeformpictureitem/d9be3906-b707-4e32-beb6-d15047085aa4_625x352.jpg?interpolation=progressive-bicubic&output-quality=90&output-format=jpeg&crop=220px:298px;0,0px image/jpeg 200 CAB5FR3MH3LHW5HIT74G4BKP6QKO4UJH - - 4467724 BL-20141215100211440-00000-12206~opera~8445.warc.gz

To make that a little more legible:

    ic.c4assets.com/brands/freeformpictureitem/d9be3906-b707-4e32-beb6-d15047085aa4_625x352.jpg?interpolation=progressive-bicubic&output-quality=90&output-format=jpeg&crop=220px:298px;0,0px
    20141215101520
    http://ic.c4assets.com/brands/freeformpictureitem/d9be3906-b707-4e32-beb6-d15047085aa4_625x352.jpg?interpolation=progressive-bicubic&output-quality=90&output-format=jpeg&crop=220px:298px;0,0px
    image/jpeg
    200
    CAB5FR3MH3LHW5HIT74G4BKP6QKO4UJH
    -
    -
    4467724
    BL-20141215100211440-00000-12206~opera~8445.warc.gz

If I do a search in the web interface for the URL 3rd field above, I get a typical calendar view with results. Clicking on any of those results, however, results in a `Resource Not In Archive` error. The only errors in the log are `logNotInArchive` lines:

    Jun 22, 2015 2:39:22 PM org.archive.wayback.webapp.AccessPoint logNotInArchive
    INFO: NotInArchive      wayback http://ic.c4assets.com/brands/freeformpictureitem/d9be3906-b707-4e32-beb6-d15047085aa4_625x352.jpg?output-quality=90&0%2C0px=&output-format=jpeg&interpolation=progressive-bicubic&crop=220px%3A298px

If, however, I alter the URL to a more simple one (e.g. `http://ic.c4assets.com/brands/this-is-a-test.jpg`) then content is replayed correctly, which suggests to me that the URL it's using to list results differs from the URL it's trying to use to replay.

We're using the `WatchedCDXSource`, however, I've replaced this with a regular `org.archive.wayback.resourceindex.cdx.CDXIndex` with no difference.

**Comment by anjackson** [comment]
Am I mistaken, or does your query URL look a bit different, containing ```output-quality=90&0%2C0px=``` rather than ```output-quality=90```

**Comment by PsypherPunk** [comment]
That isn't the query URL: I'm copying/pasting the 3rd field as above (`http://ic.c4assets.com/brands/freeformpictureitem/d9be3906-b707-4e32-beb6-d15047085aa4_625x352.jpg?interpolation=progressive-bicubic&output-quality=90&output-format=jpeg&crop=220px:298px;0,0px`).

You're right that there's a difference, however, that's coming from OpenWayback's logs. Whether that's an error in the logger or the cause of the issue, I don't know.

However, the calendar results all display the correct URL and when clicking on them the URL displays as expected (although it's logging the erroneous one).

**Comment by PsypherPunk** [comment]
Scratch this; it appears that it's a problem with our system while it proxies requests.
