### ISSUE TITLE
Display images with relative path

### ISSUE THREAD

**Issue by tumeteor** [iipc/openwayback#275]
Hi, 
sorry if this question is posted at the inappropriate place. I'm not sure if openwayback has a mechanism to rewrite urls from relative to absolute path (e.g., of images and css) so that the resources can be retrieved from the archive and shown in the website nicely. It should already a must-have feature, yet I could not find it in the documentation.

Thanks,

**Comment by ldko** [comment]
By default OpenWayback will attempt to rewrite the URLs in a page being replayed, including those of images and css, so that all content will be retrieved from the archive.
