### ISSUE TITLE
 Question about using wayback machine in windows environment

### ISSUE THREAD

**Issue by eadmead** [iipc/openwayback#278]
Hello,
I noted the installation instructions for wayback machine use recommend an operating environment for OpenWayback is UNIX/Linux and the documentation is for this.  
 Is it possible to install and use in a windows environment and are there any instructions for this?  Thank you!

**Comment by kris-sigur** [comment]
Yes, it is possible to install OpenWayback on Windows, but this is *unsupported*. I.e. this community does not expend effort on documenting the process or streamlining it.

The main issue with running OpenWayback on Windows is that building CDX indexes typically requires common *nix tools like [`sort`](http://ss64.com/bash/sort.html). 

Other than that it is just a WAR file that is deployed in a Tomcat instance.
