### ISSUE TITLE
Problems Resource not in Archive with CDX-INDEXER

### ISSUE THREAD

**Issue by rruizibai** [iipc/openwayback#325]
Hi all,

I'm upgrading OpenWayback from BDB to CDX but now OPENWAYBACK cannot replay my ARCs/WARCs. Im doing all like explain page https://github.com/iipc/openwayback/wiki/How-to-configure#cdx-indexing-or-openwayback-at-scale. I have done cdx file with cdx-indexer script and I have written path-index.txt with format ARCNAME001.arc.gz   /data/ARCS01/ARCNAME001.arc.gz

To test the installation we have only index one arc and It doesn't work, always says "Resource not in archive". I have a linux system running Tomcat 7 with Java 7, I need some help. Thank you so much.

Best Regards,
Raul

**Comment by ldko** [comment]
Hi Raul,
Thanks for letting us know you are having an issue with getting the CDX setup working.

I am currently able to index an arc.gz file with the cdx-indexer script and search and view the content in OpenWayback with Ubuntu, Tomcat 7, and Java 7. "Resource not in archive" generally means that the URL you are looking up isn't being found in the CDX file. If you know that the URL is in the CDX file, one possible cause of the error is that the CDX file isn't sorted correctly. Can you verify that you set the environment variable `LC_ALL=C` and then sorted your CDX file with the bash `sort` command after generating it?

By the way, a better place to seek help like this is via the [OpenWayback Google Group](https://groups.google.com/forum/#!forum/openwayback-dev).

Lauren

**Comment by rruizibai** [comment]
Thank you so much now it works perfectly!
