### ISSUE TITLE
BubbleCalendar.jsp missing DOCTYPE, html start tag, namespace

### ISSUE THREAD

**Issue by ldko** [iipc/openwayback#333]
Because BubbleCalendar.jsp  does not include UI-header.jsp, it lacks a DOCTYPE declaration, `<html>` start tag, namespace, etc., and produces invalid HTML. Simply including UI-header.jsp would be weird because BubbleCalendar.jsp puts in its own logo and search form. Presumably this is because the bubble calendar was added after initial Wayback development and at that point perhaps the contributor wasn't interested in retaining the look of the original header. 
Some options to fix this:
Add the necessary elements directly to BubbleCalendar.jsp
Refactor how headers are handled
other suggestions?
Brought over from the discussion in #332.

**Comment by runderwood** [comment]
@ldko Yeah. It looks a little goofy with the dual go-bars.

So much of the stuff that might go in the `head` is in the body, and I'm not really sure how much of the markup and scripting gets reused elsewhere. On those counts, I'd be for just putting a decent head in BubbleCalendar.jsp, at least for now.

**Comment by ldko** [comment]
Let's add the stuff to BubbleCalendar.jsp directly for now then.

**Comment by runderwood** [comment]
@ldko I'll drop a PR for this after #332 is merged.

**Comment by ldko** [comment]
Before opening a PR, can you add the change to src/site/markdown/release_notes.md?
