### ISSUE TITLE
Visualize snapshot density using cell background color

### ISSUE THREAD

**Issue by MohammedElsayyed** [iipc/openwayback#351]
Instead of drawing bubbles of varying size to visualize snapshot density in BubbleCalendar, it might be a good idea if all bubbles are the same size and vary background color of every bubble based on # of snapshots of every day.

This will improve user experience in terms of not overlapping an empty day between 2 days containing many snapshots.

**Comment by machawk1** [comment]
I agree that the bubble size is not the most intuitive or aesthetic representation. However, IA's deployment of Wayback uses color on their bubble calendar to signify 200s, 3XXs, etc. with blue, green, red, e.g., http://web.archive.org/web/*/http://cnn.com

I am unsure if that implementation is in OpenWayback but a gradient in color to represent seems sub-optimal as well. The gradient will need a key. A color range does not convey magnitude of quantity in the same way that bubble diameter does.

**Comment by MohammedElsayyed** [comment]
What I am thinking of gradient implementation is something like the way which github calculates contributions in stats panel. Divide snapshots, highest snapshot number - lowest snapshot number, of currently selected year into 5 categories, started from lighter blue bubble to darker one. Regarding bubble size implementation, which is the current model in BubbleCalendar's OpenWayback, the bubble size increases until a certain # of snapshots, then the bubble size saturates and doesn't give an exact indication of how many snapshots the day contains.

You can freely give it a quick look at [this sample](http://web.archive.bibalex.org/web/20110701000000*/http://cnn.com) and let me know your findings. Be easy as I didn't finish the legend, at the bottom-right, in terms of CSS as it requires many enhancements.

Please let me know whether there is a better implementation to start working on before creating a pull request. Thanks for feedback!

**Comment by ldko** [comment]
Regarding the @machawk1 comment "unsure if that implementation is in OpenWayback," OpenWayback doesn't use different colors for different types of status codes. They are just blue. The example at http://web.archive.org/web/*/http://cnn.com is interesting. Bubbles show as green even if when you hover over the day, the visible list of days (which also shows different colors) that appears only has one of the capture dates showing green. ¯\_(ツ)_/¯

ANYONE else using the bubble calendar want to get an opinion in on the [issue](https://github.com/iipc/openwayback/issues/351) of keeping bubble diameter as representing number of captures or changing to use a gradient similar to GitHub contributions visualization?

**Comment by MohammedElsayyed** [comment]
It has been deployed on [BA's cluster](http://web.archive.bibalex.org/web/).

@ldko should I make a pull request?

**Comment by ldko** [comment]
@MohammedElsayyed yes, you could go ahead and make a PR. It would be good if you or I put out a message on the openwayback-dev Google list to see if anyone there has an opinion on the new representation of capture numbers on the Bubble Calendar with a link to it. I am hesitant to merge it without some level of consensus on it being preferred to the current implementation. Thank you!

**Comment by MohammedElsayyed** [comment]
I put a message on the openwayback-dev. Next few days, will make a PR.

Thanks!
