### ISSUE TITLE
Toolbar stomping on jQuery again

### ISSUE THREAD

**Issue by ldko** [iipc/openwayback#356]
The problem introduced about stomping on jQuery with the Toolbar.jsp in #48 and fixed in #210
 was reintroduced in #341 when we added back jQuery to the toolbar. Using the default toolbar is back to causing issues for some replayed pages. I think we need to re-remove the jQuery dependency in Toolbar.jsp.

**Comment by ldko** [comment]
@MohammedElsayyed Do you want to look at a solution for removing the jQuery dependency from the Toolbar?

**Comment by MohammedElsayyed** [comment]
@ldko I will be happy to work on it, but I already have many tasks should be done.
