### ISSUE TITLE
jspInserts not loading in proper location

### ISSUE THREAD

**Issue by jason-ellis** [iipc/openwayback#360]
I'm not sure how prevalent this issue is, but it is noticeable when archiving this page: http://glasstire.com

Normally, `/WEB-INF/replay/Disclaimer.jsp` is printed immediately following the opening `<body>` tag. In the page above, it's printed inside of a `<noscript>` tag that appears in the head in the live site.

This prevents the relevant code from executing to add the disclaimer to the top of the page.

**Comment by ldko** [comment]
#319 seems relevant
