### ISSUE TITLE
Toolbar plurality issue when only a single capture

### ISSUE THREAD

**Issue by machawk1** [iipc/openwayback#372]
If only one capture exists for a URI-R, the web UI toolbar states, "1 captures", an incorrect plurality.
<img width="97" alt="screen shot 2018-02-04 at 12 00 29 am" src="https://user-images.githubusercontent.com/2514780/35774468-73110c48-093e-11e8-8929-7f8bf0abf2d7.png">

This stems from `wayback-webapp/src/main/webapp/WEB-INF/replay/Toolbar.jsp` reading `ToolBar.numCapturesTitle` from `wayback-webapp/src/main/resources/WaybackUI.properties` and providing a formatted value that does not affect the "captures" literal of the formatted string.

OpenWayback 2.3.2

**Comment by anjackson** [comment]
Hm, I find [ChoiceFormat]() a bit confusing, but it would seem the syntax we need for [this](https://github.com/iipc/openwayback/blob/6475121cef79240b5e18a5f2c224ff9ba933b43d/wayback-core/src/test/resources/WaybackUI.properties#L171) is:

    ToolBar.numCapturesText={0} {0,choice,0#captures|1#capture|1<captures} 

n.b. I've not had a chance to test this yet.

**Comment by ldko** [comment]
Hi @machawk1 , thanks for reporting the issue. Do you want to submit a PR to fix this?

**Comment by machawk1** [comment]
That fix works for me, @anjackson.

<img width="97" alt="screen shot 2018-02-05 at 11 47 52 am" src="https://user-images.githubusercontent.com/2514780/35817097-74bbd8de-0a6a-11e8-9f28-2290a4d27a30.png">

<img width="99" alt="screen shot 2018-02-05 at 11 53 47 am" src="https://user-images.githubusercontent.com/2514780/35817413-4cdef4ee-0a6b-11e8-88f0-2731f4a520dc.png">


I'll submit a PR, @ldko .

**Comment by machawk1** [comment]
PR submitted as #373. /cc @ldko

**Comment by ldko** [comment]
Thanks @machawk1 and @anjackson !
