### ISSUE TITLE
Searching URL with language like arabic is bugged (encoding problem?)

### ISSUE THREAD

**Issue by loredra** [iipc/openwayback#386]
In my case, after a bare-minimum setup following the [official guide](https://github.com/iipc/openwayback/wiki/How-to-configure), I am unable to search for the below URL
`(https://mawdoo3.com/كيف_أتخلص_من_قلق_الامتحانات)`

The step to create that warc:
1. Use https://webrecorder.io/
2. Place it into the data folder specified in way-back.xml

The search by copying the entire URL returns nothing with the query parameter in url wrongly return ?????

For a quick look at the problem , we can go to http://web.archive.bibalex.org/web/ and copy the above link into the search box.

**Comment by ldko** [comment]
I have been able to replicate the issue. I am able to access the archived page directly from a WARC created using Heritrix at
`http://localhost:8080/wayback/20181106204004/https://mawdoo3.com/كيف_أتخلص_من_قلق_الامتحانات`

and I can search successfully for the percent encoded URL in the search box with:
`https://mawdoo3.com/%D9%83%D9%8A%D9%81_%D8%A3%D8%AA%D8%AE%D9%84%D8%B5_%D9%85%D9%86_%D9%82%D9%84%D9%82_%D8%A7%D9%84%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%D8%A7%D8%AA`

However, if I submit `https://mawdoo3.com/كيف_أتخلص_من_قلق_الامتحانات` in the search box, the response comes back at `http://localhost:8080/wayback/19960101000000-20181231235959*/https://mawdoo3.com/???_?????_??_???_??????????`

Thanks for reporting the issue. Pull requests are welcome.

**Comment by ldko** [comment]
I was looking at this again and now I am not able to replicate the issue when deploying OpenWayback locally with the default configuration. I can search https://mawdoo3.com/كيف_أتخلص_من_قلق_الامتحانات and the result shows up as expected. However, when I search at  http://web.archive.bibalex.org/web/, I see the problem with the response from the search having the url incorrect. @MohammedElsayyed have you looked at this?

**Comment by ato** [comment]
I was able to reproduce this by building the master branch, running it under jetty with no configuration changes and dropping the warc into /tmp/openwayback/files1 so that it's automatically indexed.

I attached a debugger and I think the problem is here:

https://github.com/iipc/openwayback/blob/c49f8e7200870c3af40561f3ca340c67c98db02f/wayback-core/src/main/java/org/archive/wayback/exception/BetterRequestException.java#L116

Setting a breakpoint on tat line reveals the current value of variable `redirectURI` is:

     http://localhost:8080/wayback/19960101000000-20191231235959*/https://mawdoo3.com/كيف_أتخلص_من_قلق_الامتحانات

Note that this is not percent escaped. This is then inserted directly into the Location header. Jetty is presumably then replacing the non-ASCII characters with question marks when it serializes the header.

**Comment by anjackson** [comment]
So something like:

```
    response.setHeader("Location", URLEncoder.encode(redirectURI,"UTF-8")); 
```

I guess?

**Comment by anjackson** [comment]
Hm, yes, I think that's right. Sorry that was probably a bad suggestion.

**Comment by ldko** [comment]
I welcome any suggestions @anjackson  :).

**Comment by MohammedElsayyed** [comment]
I was off last 3 months for some reason. I am back to work last week. I have a lot in my plate actually. I should give it a look as soon as possible.

**Comment by ato** [comment]
I tried this which I'm not totally sure is correct but it seems to do what we want:

```java
redirectURI = new URL(redirectURI).toURI().toASCIIString();
```
and the redirect now goes to

`http://localhost:8080/wayback/19960101000000-20191231235959*/https://mawdoo3.com/%D9%83%D9%8A%D9%81_%D8%A3%D8%AA%D8%AE%D9%84%D8%B5_%D9%85%D9%86_%D9%82%D9%84%D9%82_%D8%A7%D9%84%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86%D8%A7%D8%AA`

which renders the characters correctly in the browser's URL bar. However Wayback still returns resource not in archive. Using a prefix search I find that Wayback actually indexed it with this totally different encoding that appears as garbage characters in the address bar:

`http://localhost:8080/wayback/20190122144925/https://mawdoo3.com/%C3%99%C2%83%C3%99%C2%8A%C3%99%C2%81_%C3%98%C2%A3%C3%98%C2%AA%C3%98%C2%AE%C3%99%C2%84%C3%98%C2%B5_%C3%99%C2%85%C3%99%C2%86_%C3%99%C2%82%C3%99%C2%84%C3%99%C2%82_%C3%98%C2%A7%C3%99%C2%84%C3%98%C2%A7%C3%99%C2%85%C3%98%C2%AA%C3%98%C2%AD%C3%98%C2%A7%C3%99%C2%86%C3%98%C2%A7%C3%98%C2%AA`

I haven't tried with a CDX index so its possible this %C3... encoding may be a second separate bug that only affects the BDB index.

**Comment by ldko** [comment]
Running OpenWayback in Docker I was able to reproduce the original reported issue of the URL coming back full of `?????`s.

@ato, I tried your suggested fix and was able to search for and view the page successfully. I did not get the resource not in archive that you mentioned getting.
