### ISSUE TITLE
Recursive discovery of WARC files do not seem to work

### ISSUE THREAD

**Issue by peterk** [iipc/openwayback#388]
Running the latest iipc/openwayback image in Docker. Adding WARC files to /data/files2 works if I put them directly in the root. Adding WARC files in a folder structure (e.g. /data/files2/myfiles/test/example.warc) and they will not be picked up in synchronization. The [documentation here](https://github.com/iipc/openwayback/wiki/How-to-configure)  says "OpenWayback will search these two directories recursively." but that does not seem to be the case?

**Comment by ibnesayeed** [comment]
The documentation should be updated here because in the the default configuration file `BDBCollection.xml` the `recurse` property is set to false. This, however, means it is possible to enable recursion by supplying a custom config file inside the docker container.

```xml
  <bean id="datadirs" class="org.springframework.beans.factory.config.ListFactoryBean">
    <property name="sourceList">
      <list>
        <bean class="org.archive.wayback.resourcestore.resourcefile.DirectoryResourceFileSource">
          <property name="name" value="files1" />
          <property name="prefix" value="${wayback.archivedir.1}" />
          <property name="recurse" value="false" />
        </bean>
        <bean class="org.archive.wayback.resourcestore.resourcefile.DirectoryResourceFileSource">
          <property name="name" value="files2" />
          <property name="prefix" value="${wayback.archivedir.2}" />
          <property name="recurse" value="false" />
        </bean>
      </list>
    </property>
  </bean>
```

**Comment by ibnesayeed** [comment]
I have updated the wiki page now.

**Comment by peterk** [comment]
Thank you! Custom config setting works. Closing this issue.
