### ISSUE TITLE
WARNING: No PortMapper for port 80

### ISSUE THREAD

**Issue by jafamo** [iipc/openwayback#393]
I installed openwayback-2.3.2.war with apache-tomcat-8.5.38 as ROOT webapp.

My wayback.xml config file:
```
wayback.basedir.default=/tmp/openwayback
wayback.url.scheme.default=http
wayback.url.host.default=localhost
wayback.url.port.default=8080
        
wayback.basedir=#{ systemEnvironment['WAYBACK_BASEDIR'] ?: '${wayback.basedir.default}' }
wayback.url.scheme=#{ systemEnvironment['WAYBACK_URL_SCHEME'] ?: '${wayback.url.scheme.default}' }
wayback.url.host=#{ systemEnvironment['WAYBACK_URL_HOST'] ?: '${wayback.url.host.default}' }
wayback.url.port=#{ systemEnvironment['WAYBACK_URL_PORT'] ?: '${wayback.url.port.default}' }

wayback.url.prefix.default=${wayback.url.scheme}://${wayback.url.host}:${wayback.url.port}
wayback.url.prefix=#{ systemEnvironment['WAYBACK_URL_PREFIX'] ?: '${wayback.url.prefix.default}' }

wayback.archivedir.1=/opt/WARCS/


 <bean id="resourcefilelocationdb" class="org.archive.wayback.resourcestore.locationdb.FlatFileResourceFileLocationDB">
    <property name="path" value="/opt/path-index-tmp.txt" />
  </bean>

<import resource="CDXCollection.xml"/>

```

My error from catalina.out:
```
Mar 04, 2019 9:31:33 AM org.archive.wayback.util.webapp.RequestMapper mapRequest
WARNING: No PortMapper for port 80
```

I tried port 80,8080 but not working properly.
![imagen](https://user-images.githubusercontent.com/3945078/53721034-7a3c4c80-3e62-11e9-8478-08bac2389d1f.png)

any idea ?

Regards,
xavi

**Comment by anjackson** [comment]
If you've configured Tomcat to listen on port 80, you'll need to change `wayback.url.port.default` to match:

```
wayback.url.port.default=80
```

**Comment by ldko** [comment]
As, @anjackson mentions, port 80 wouldn't be serving OpenWayback if you have `wayback.url.port.default=8080` in your configuration. It looks like from your comment that you also tried 8080, and it wasn't working either. Looking at the 404 screenshot, it looks to me like you would have been trying the URL http://localhost:8080/query to reach that screen. The default home page for the application should be http://localhost:8080/wayback/. Does that URL work for you? If not, did you change anything in your `standardaccesspoint` bean?

**Comment by jafamo** [comment]
Hi, @anjackson  & @ldko I resolved my problem.
I change in my wayback.xml
 ```
<!-- <property name="replayPrefix" value="${wayback.url.prefix}/wayback/" />-->
    <property name="replayPrefix" value="http://mydomain:8080/wayback/" />
<!--    <property name="queryPrefix" value="${wayback.url.prefix}/wayback/" /> -->
    <property name="queryPrefix" value="http://mydomain:8080/wayback/" />
 <!--   <property name="staticPrefix" value="${wayback.url.prefix}/wayback/" /> -->
    <property name="staticPrefix" value="http://mydomain:8080/wayback/" />
```

Thanks,
jafamo.
