### ISSUE TITLE
Rewrite new imagesrcset attribute of the link element

### ISSUE THREAD

**Issue by ibnesayeed** [iipc/openwayback#394]
The `<link>` element has a new attribute called `imagesrcset` which can be used for preloading resources with proper resolution. This is similar to the `srcset` attribute of the `<img>` element. [The support for this attribute landed in Chrome 73](https://developers.google.com/web/updates/2019/03/nic73#more). I think entries of this attribute should also be rewritten in the same way `srcset` is done.

**Comment by ldko** [comment]
Thanks for opening the issue @ibnesayeed . It makes sense to rewrite this. Do you want to do a PR for it? If it works the same as `srcset` I presume it could use the `SrcsetStringTransformer` introduced in #311 and be rewritten with small edits to the same files modified in #382.
