### ISSUE TITLE
Unable to index WARC-Target-URI with angle brackets (as produced by newer versions of wget)

### ISSUE THREAD

**Issue by qome** [iipc/openwayback#421]
Does the following error message mean a page was not imported:
```plain
[2020-01-12 21:20:05] [info] WARNING: FAILED canonicalize(<https://abs.twimg.com/a/1576611360/css/t1/images/ui-bg_flat_0_aaaaaa_40x100.png>)
```

I can't get anything to actually show up in searches even though they're in the WARCs that are being imported.

**Comment by qome** [comment]
It seems that contents of WARCs I create with wget on Debian 9 can be displayed through OpenWayback on either Debian 9 or Debian 10. WARCs I create on Debian 10 cannot be displayed in either.

Is there a way to resolve this issue in my OpenWayback instance?

**Comment by ato** [comment]
It appears that wget creates invalid WARC files with the value of the WARC-Target-URI field incorrectly enclosed in angle brackets:

    WARC-Target-URI: <http://example.com/>

**Comment by ato** [comment]
Looks like pywb has support for wget-style WARCs: https://github.com/webrecorder/pywb/issues/294

**Comment by qome** [comment]
Strange, thanks for identifying the problem. Internet Archive has a [proxy](internetarchive/warcprox) that I can use with wget to generate compliant WARCs and for now I'll use that since it seems to be getting updated regularly and is a pretty neat drop-in in front of any old web browser or web downloader like wget.
