### ISSUE TITLE
using s3 buckets?

### ISSUE THREAD

**Issue by chichicuervo** [iipc/openwayback#425]
there are a few mentions of S3 bucket support in 2015.  Does it actually work, and if so, how do I configure so it will actually work?

**Comment by ldko** [comment]
HI @chichicuervo, the support for S3 buckets was contributed from someone outside of IIPC via #188 and #189, but as far as I know, there was no documentation provided for it. The code to support it is still in [ResourceFactory](https://github.com/iipc/openwayback/blob/master/wayback-core/src/main/java/org/archive/wayback/resourcestore/resourcefile/ResourceFactory.java). It indicates credentials would go into $HADOOP_CONF/core-site.xml. Other than that, I would try to configure it per the [CDX instructions in the wiki](https://github.com/iipc/openwayback/wiki/How-to-configure#cdx-indexing-or-openwayback-at-scale) and using a `FlatFileResourceFileLocationDB` (path-index.txt) as described there, that had the addresses of the WARCs in the S3 buckets.

**Comment by chichicuervo** [comment]
yeah... the lack of documentation is kind of the problem.  Particularly since the hadoop stuff neither makes any sense to me (not a java dev) or does the link mentioned in previous issues point to anything but a 404

**Comment by ldko** [comment]
It looks like the Internet Archive has an [archived copy](https://web.archive.org/web/20150123215117/https://wiki.apache.org/hadoop/AmazonS3) of that page from around the time that shows key configuration.

**Comment by chichicuervo** [comment]
for reference's sake... this didn't work.. attempting to go the CDX route
