### ISSUE TITLE
calendar view does not work with outbackcdx

### ISSUE THREAD

**Issue by vitezg** [iipc/openwayback#438]
When using outbackcdx, the calendar view (captureJsp property of org.archive.wayback.query.Renderer) misbehaves: the clickable yearly view does not respond to clicks anymore. Pywb works well with the same outbackcdx. Any ideas what can cause this?

Openwayback's outbackcdx configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans-3.0.xsd"
       default-init-method="init">
  <bean id="remotecollection" class="org.archive.wayback.webapp.WaybackCollection">

    <property name="resourceStore">
      <bean class="org.archive.wayback.resourcestore.LocationDBResourceStore">
        <property name="db" ref="resourcefilelocationdb" />
      </bean>
    </property>
    <property name="resourceIndex">
      <bean class="org.archive.wayback.resourceindex.RemoteResourceIndex">
        <property name="searchUrlBase" value="http://127.0.0.1:8538/pywb" />
      </bean>
    </property>
  </bean>
</beans>
```

Openwayback with CDX:
![openwayback-cdx](https://user-images.githubusercontent.com/745368/111620729-036f1380-87df-11eb-8f9c-406e8c4f67d2.png)
With outbackcdx:
![openwayback-outbackcdx](https://user-images.githubusercontent.com/745368/111621695-336ae680-87e0-11eb-951f-f863458e573a.png)

**Comment by ldko** [comment]
Thanks for reporting this issue @vitezg . I was able to reproduce a calendar problem with OutbackCDX and OpenWayback, while the calendar view still worked for me with OpenWayback and its EmbeddedCDXServerIndex. When using with OutbackCDX, clicking other dates on the timeline did actually link me to a URL containing a different date, but the calendar would still show the results for 2021.

From my understanding @kris-sigur is running OpenWayback with OutbackCDX and the calendar I see at https://vefsafn.is/?page=wayback-results&site=https://landsbokasafn.is/ seems to be functioning properly, so I am not sure if Kris is using different calendar code.

I haven't had a chance to look closely at this, but I am wondering if @kris-sigur or @ato has any thoughts about it.

**Comment by ato** [comment]
Looks like BubbleCalendar relies on a boolean element 'closest' in CDX results to determine the actively selected year and without that present it defaults to the last year:

https://github.com/iipc/openwayback/blob/c7fac11479ee4447a71ee337f91018f7808757a2/wayback-core/src/main/java/org/archive/wayback/partition/BubbleCalendarData.java#L126-L141

It seemingly expects the CDX server to calculate the closest snapshot to a given date and flag it appropriately. We (NLA) didn't use that view and it seems like Kris' works differently and updates the selected year client-side in JavaScript rather than changing the url.

I'll see if I can add support for this.

**Comment by ato** [comment]
I've now released [OutbackCDX 0.10.0](https://github.com/nla/outbackcdx/releases/tag/0.10.0) which adds support for `closest` result xml element. This seems to fix the problem in my local testing.

**Comment by vitezg** [comment]
The new version fixes the issue here too.

**Comment by ldko** [comment]
Thanks for the quick fix @ato! Thanks for verifying it and reporting back @vitezg !
