### ISSUE TITLE
indexing one .warc file need help

### ISSUE THREAD

**Issue by mashalahmad** [iipc/openwayback#439]
I have successfully configured openwayback but I am confused where should I put the .warc file and how can I access it then?

**Comment by ldko** [comment]
Hi @mashalahmad , where you put your .warc file depends on how you have configured OpenWayback. Please see https://github.com/iipc/openwayback/wiki/How-to-configure#the-bare-essentials-or-how-to-use-the-bdb-indexing.

If you are using the default configuration, based on the default values for `wayback.basedir.default` and `wayback.archivedir.1` and `wayback.archivedir.2` in the WEB-INF/wayback.xml, you would put your .warc file(s) in either a directory at `/tmp/openwayback/files1` or `/tmp/openwayback/files2`. The WARC files in those locations will be automatically indexed, allowing you to search for a URL that is in your WARC via the search bar at http://localhost:8080/wayback/.

Note: If you are running OpenWayback for more than testing purposes, you would want to change the base directory out of /tmp.

Let us know if you have a different configuration, and we can try to help with that. Thanks!

**Comment by mashalahmad** [comment]
@idko Thanks for reply. I setup the tomcat and then after downlaoding rename the openwayback2.4.0 as root.war and then put the .warc file inside the tmp/openwayback/files1 . Now just to clear myself there was no files1 folder inside the tmp/openwayback so I created on and then put the .warc file inside and I also delelted the other folder e.g. file-db. index and index data. and I checked inside the state folder my test.warc file is listed in incoming folder and files1.txt file. but when I searched it with the url it says resource not found.

**Comment by mashalahmad** [comment]
and to just give you a small background I installed tomcat following [this link]( https://cloudwafer.com/blog/installing-apache-tomcat-on-ubuntu/) so currently another user(with name of tomcat) is added on Ubuntu. I unzip OWB.war inside that tomcat user account and also put my .warc files inside the user tmp/openwayback folder.Will it be a non root context installation?

**Comment by ldko** [comment]
If you renamed the .war file ROOT.war when [installing it](https://github.com/iipc/openwayback/wiki/How-to-install#installation), it would be in the ROOT context and the interface would be at http://localhost:8080/wayback/. If you renamed the .war web application file OWB.war instead of ROOT.war when deploying, it would not be the ROOT context.

I think you do need to create the /tmp/openwayback/files1 directory as you did. Regarding deleting the file-db, index, and index-data directories, did you restart Tomcat after this? You will need those directories to exist for the search to work.

**Comment by mashalahmad** [comment]
Thanks @ldko  for clarification. So after deleting file-db, index and index-data I restarted the tomcat and these folders were recreated. Another thing I noticed is whenever I put my .warc file in files1 folder it is disappearing. is it something related to read/write permission?

**Comment by ldko** [comment]
If you are able to put your .warc file in initially, I don't think it would be read/write permissions that would cause it to disappear. Data in the /tmp directory does not persist generally--such as after a reboot. At what point is your warc disappearing. You could try changing your `wayback.basedir.default` to a different directory that shouldn't be deleted even after a reboot. What operating system are you using?

**Comment by mashalahmad** [comment]
@ldko Sorry for late reply, Initially I try to install it on Ubuntu 16.04 but I was not able to see the indexed files. Now I am trying on  Ubuntu 20.4.1 and problem is Im not able to even locate tmp/openwayback folder. I try to configure wayback.xml but when I change the location of wayback.basedir.default I got 404 error. I installed tomcat9 and maven 3.6.3

**Comment by mashalahmad** [comment]
Finally I was able to see the indexed file but when I click on it it just give error resource not available. Im using Conifer(web recorder) to record the web pages. Im ataching the pic too.
![Screenshot from 2021-06-18 14-43-27](https://user-images.githubusercontent.com/31829812/122570599-cb78a600-d043-11eb-986d-2c2f4a302cc1.png)
![Screenshot from 2021-06-18 14-45-23](https://user-images.githubusercontent.com/31829812/122570650-d9c6c200-d043-11eb-944c-0906106dccf1.png)

**Comment by ldko** [comment]
Hi @mashalahmad , have you checked to see if there is an error message or something helpful in the logs? Errors should be logged in your Tomcat logs directory in a file named catalina.out.

Also, IIPC now recommends using Webrecorder's [pywb for replay over OpenWayback](https://netpreserveblog.wordpress.com/2020/12/16/openwayback-to-pywb-transition-guide/), so you may want to try [replaying your WARCs in pywb](https://netpreserveblog.wordpress.com/2020/12/16/openwayback-to-pywb-transition-guide/) instead. pywb is under active development and thus provides better replay quality. Also, Conifer makes use of Webrecorder software, so this is another reason it might make sense to try pywb.

**Comment by mashalahmad** [comment]
hi @ldko  I checked and found this error

org.archive.wayback.exception.ResourceNotAvailableException: /tmp/openwayback/files1/dri-2021061813242dri-20210618132425.warcdri-20210618132425.warc5.warc - java.io.IOException: Failed to find WARC MAGIC
at org.archive.wayback.resourcestore.LocationDBResourceStore.retrieveResource(LocationDBResourceStore.java:96)
	at org.archive.wayback.webapp.AccessPoint$SingleLoadResourceStore.retrieveResource(AccessPoint.java:639)
	at org.archive.wayback.webapp.AccessPoint.handleReplay(AccessPoint.java:886)
	at org.archive.wayback.webapp.AccessPoint.handleRequest(AccessPoint.java:314)
	at org.archive.wayback.util.webapp.RequestMapper.handleRequest(RequestMapper.java:198)
	at org.archive.wayback.util.webapp.RequestFilter.doFilter(RequestFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)


I have placed the warc file in files1 folder.  Warc file name is dri-20210618132425.warc and I searched it on web with http://dri.ie
Am I doing it right? File is not searchable with name but with address of website.

**Comment by anjackson** [comment]
This looks like an issue arising because some tools write WARC that are Gzip compressed but only use the .warc suffix. OWB doesn't cope with this, and needs the WARC to be named whatever.warc.gz

**Comment by mashalahmad** [comment]
@anjackson  Thanks man you solved my problem. Changing the extension solved my problem. I have one last question how can I customise the openwayback to just display the record present for that specific year not all the years with no records showing 0 pages.

**Comment by ldko** [comment]
@mashalahmad I assume when you mention "no records showing 0 pages" you are referring to the CalendarResults.jsp results page? [That and other options](https://github.com/iipc/openwayback/tree/master/wayback-webapp/src/main/webapp/WEB-INF/query) for showing the search results should be in the `WEB-INF/query/` directory of a deployed OpenWayback instance. You can also configure which of those jsp files gets used for the display in your wayback.xml file.
