### ISSUE TITLE
Extra Wayback prefix?

### ISSUE THREAD

**Issue by eeeps** [iipc/openwayback#440]
CSS-Tricks puts Cloudinary infront of its ad image URLs, to optimize them. The Wayback Machine seems to be prefixing both the full URL and the URL-within-the-URL, but... weirdly.

e.g.:

Here's an ad URL:

`https://cdn4.buysellads.net/uu/7/87054/1617221891-335-600x600-buy-sell-banner-personalization.jpg`

CSS-Tricks prefixes that URL with Cloudinary in production, so here's the URL that the Wayback Machine saw in an `<img src>` on https://css-tricks.com/super-tiny-icons/ on November 30th, 2020: 

`https://res.cloudinary.com/css-tricks/image/fetch/w_600,q_auto,f_auto/
https://cdn4.buysellads.net/uu/7/87054/1617221891-335-600x600-buy-sell-banner-personalization.jpg`

And then here's how that gets transformed, when I look at http://web.archive.org/web/20201130221736/https://css-tricks.com/super-tiny-icons/:

`http://web.archive.org/web/20201130224033/https://res.cloudinary.com/css-tricks/image/fetch/w_600,q_auto,f_auto/http://web.archive.org/web/20210405180528/https://cdn4.buysellads.net/uu/7/87054/1617221891-335-600x600-buy-sell-banner-personalization.jpg`

The original URL now has three prefixes: ① Wayback from requested date → ② Cloudinary → ③ Wayback from today’s date?? →  ④ original ad URL

① http://web.archive.org/web/20201130224033/
② https://res.cloudinary.com/css-tricks/image/fetch/w_600,q_auto,f_auto/
③ http://web.archive.org/web/20210405180528/
④ https://cdn4.buysellads.net/uu/7/87054/1617221891-335-600x600-buy-sell-banner-personalization.jpg

Whereas I would only expect two (①②④). How is ③ getting inserted?

It causes two problems:

- Sometimes, the ad isn't in the most recent crawl, and broken images show up in the Wayback machine.
- Cloudinary ends up fetching _many_ copies of the image, each with slightly different Wayback machine prefixes (instead of just one copy, from the original server) (and then the Wayback machine proxies each of those...)

Is this a bug? Something that can be worked around?

**Comment by ldko** [comment]
Hi @eeeps , from the description of the issue reported, it seems like you are seeing the problem specifically in the Wayback Machine at http://web.archive.org. If that is the case, this is no longer the repo for the application served at web.archive.org. Internet Archive has different software they now use for their Wayback Machine (closed source I think). If I am misunderstanding, and you are running an instance of OpenWayback and are seeing this issue, please let me know.

Thanks,
Lauren

**Comment by eeeps** [comment]
@idko apologies and thanks. If you have any tips on where might be better to report, I'm all ears (but I know that isn't your job!)

**Comment by ldko** [comment]
I am not sure how they like issues reported. Perhaps if @kngenie is still working on the project, he could be of help?

**Comment by kngenie** [comment]
Hi @eeeps, thx for reporting the issue. We don't have an open forum for our 5th-gen wayback machine yet, but we welcome bug reports at `info` at `archive.org`. We took note of this particular issue, thanks to someone that forwarded a link to me.
